Parameters:
  SsmParameterValueamplifyuserC96584B6F00A464EAD1953AFF4B05118Parameter:
    Type: AWS::SSM::Parameter::Value<String>
    Default: amplify-user
  SsmParameterValueamplifyrepoC96584B6F00A464EAD1953AFF4B05118Parameter:
    Type: AWS::SSM::Parameter::Value<String>
    Default: amplify-repo
Resources:
  MyAppRole2E93CCE5:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: MyAmplifyAppStack/MyApp/Role/Resource
  MyApp3CE31C26:
    Type: AWS::Amplify::App
    Properties:
      Name: MyApp
      BuildSpec: >-
        {
          "version": "1.0",
          "frontend": {
            "Phases": {
              "PreBuild": {
                "Commands": [
                  "yarn"
                ]
              },
              "Build": {
                "Commands": [
                  "yarn build"
                ]
              }
            },
            "Artifacts": {
              "BaseDirectory": "public",
              "Files": "**/*"
            }
          }
        }
      IAMServiceRole:
        Fn::GetAtt:
          - MyAppRole2E93CCE5
          - Arn
      OauthToken: "{{resolve:secretsmanager:my-github-token:SecretString:::}}"
      Repository:
        Fn::Join:
          - ""
          - - https://github.com/
            - Ref: SsmParameterValueamplifyuserC96584B6F00A464EAD1953AFF4B05118Parameter
            - /
            - Ref: SsmParameterValueamplifyrepoC96584B6F00A464EAD1953AFF4B05118Parameter
    Metadata:
      aws:cdk:path: MyAmplifyAppStack/MyApp/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.56.0,@aws-cdk/assets=1.56.0,@aws-cdk/aws-amplify=1.56.0,@aws-cdk/aws-cloudformation=1.56.0,@aws-cdk/aws-cloudwatch=1.56.0,@aws-cdk/aws-codebuild=1.56.0,@aws-cdk/aws-codecommit=1.56.0,@aws-cdk/aws-codeguruprofiler=1.56.0,@aws-cdk/aws-ec2=1.56.0,@aws-cdk/aws-ecr=1.56.0,@aws-cdk/aws-ecr-assets=1.56.0,@aws-cdk/aws-efs=1.56.0,@aws-cdk/aws-events=1.56.0,@aws-cdk/aws-iam=1.56.0,@aws-cdk/aws-kms=1.56.0,@aws-cdk/aws-lambda=1.56.0,@aws-cdk/aws-logs=1.56.0,@aws-cdk/aws-s3=1.56.0,@aws-cdk/aws-s3-assets=1.56.0,@aws-cdk/aws-sam=1.56.0,@aws-cdk/aws-secretsmanager=1.56.0,@aws-cdk/aws-sns=1.56.0,@aws-cdk/aws-sqs=1.56.0,@aws-cdk/aws-ssm=1.56.0,@aws-cdk/cloud-assembly-schema=1.56.0,@aws-cdk/core=1.56.0,@aws-cdk/custom-resources=1.56.0,@aws-cdk/cx-api=1.56.0,@aws-cdk/region-info=1.56.0,jsii-runtime=DotNet/3.1.6/.NETCoreApp,Version=v3.1/1.0.0.0
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

