Resources:
  myuserpoolsmsRole0E16FDD9:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: MyCognitoUserPoolStackmyuserpool5272DE15
            Effect: Allow
            Principal:
              Service: cognito-idp.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyDocument:
            Statement:
              - Action: sns:Publish
                Effect: Allow
                Resource: "*"
            Version: "2012-10-17"
          PolicyName: sns-publish
    Metadata:
      aws:cdk:path: MyCognitoUserPoolStack/myuserpool/smsRole/Resource
  myuserpool01998219:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_phone_number
            Priority: 1
          - Name: verified_email
            Priority: 2
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AliasAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      EmailVerificationMessage: Hello {username}, Thanks for signing up to our awesome app! Your verification code is {####}
      EmailVerificationSubject: Verify your email for our awesome app!
      SmsConfiguration:
        ExternalId: MyCognitoUserPoolStackmyuserpool5272DE15
        SnsCallerArn:
          Fn::GetAtt:
            - myuserpoolsmsRole0E16FDD9
            - Arn
      SmsVerificationMessage: Hello {username}, Thanks for signing up to our awesome app! Your verification code is {####}
      UserPoolName: MyUserPool
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailMessage: Hello {username}, Thanks for signing up to our awesome app! Your verification code is {####}
        EmailSubject: Verify your email for our awesome app!
        SmsMessage: Hello {username}, Thanks for signing up to our awesome app! Your verification code is {####}
    Metadata:
      aws:cdk:path: MyCognitoUserPoolStack/myuserpool/Resource
  myuserpoolCognitoDomain3CADA6A3:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: my-awesome-app
      UserPoolId:
        Ref: myuserpool01998219
    Metadata:
      aws:cdk:path: MyCognitoUserPoolStack/myuserpool/CognitoDomain/Resource
  myuserpoolMyUserPoolClient0770E761:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: myuserpool01998219
      AllowedOAuthFlows:
        - implicit
        - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - profile
        - phone
        - email
        - openid
        - aws.cognito.signin.user.admin
      CallbackURLs:
        - https://example.com
      SupportedIdentityProviders:
        - COGNITO
    Metadata:
      aws:cdk:path: MyCognitoUserPoolStack/myuserpool/MyUserPoolClient/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.54.0,@aws-cdk/assets=1.53.0,@aws-cdk/aws-certificatemanager=1.53.0,@aws-cdk/aws-cloudformation=1.53.0,@aws-cdk/aws-cloudwatch=1.53.0,@aws-cdk/aws-codeguruprofiler=1.53.0,@aws-cdk/aws-cognito=1.53.0,@aws-cdk/aws-ec2=1.53.0,@aws-cdk/aws-efs=1.53.0,@aws-cdk/aws-events=1.53.0,@aws-cdk/aws-iam=1.53.0,@aws-cdk/aws-kms=1.53.0,@aws-cdk/aws-lambda=1.53.0,@aws-cdk/aws-logs=1.53.0,@aws-cdk/aws-route53=1.53.0,@aws-cdk/aws-s3=1.53.0,@aws-cdk/aws-s3-assets=1.53.0,@aws-cdk/aws-sns=1.53.0,@aws-cdk/aws-sqs=1.53.0,@aws-cdk/aws-ssm=1.53.0,@aws-cdk/cloud-assembly-schema=1.53.0,@aws-cdk/core=1.53.0,@aws-cdk/custom-resources=1.53.0,@aws-cdk/cx-api=1.53.0,@aws-cdk/region-info=1.53.0,jsii-runtime=DotNet/3.1.6/.NETCoreApp,Version=v3.1/1.0.0.0
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

